package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'ReleaseNotesVcs'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("ReleaseNotesVcs")) {
    val expected = GitVcsRoot({
        id("ReleaseNotesVcs")
        name = "release-notes"
        url = "https://github.com/Varshraghu98/release-notes.git"
        branch = "refs/heads/main"
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        userNameStyle = GitVcsRoot.UserNameStyle.NAME
        userForTags = "%env.BUILD_NUMBER%"
    }

}
